name: buildwf

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone le repo
        uses: actions/checkout@v3
      - name: Install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xml, pdo_sqlite, intl
      - name: install composer dep
        run:  composer install --no-progress --prefer-dist --optimize-autoloader 
      - name: Run tests
        run: ./vendor/bin/phpunit
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hadnotb/neeewimage:latest
          
    
