name: buildwf
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone le repo 
        uses: actions/checkout@v3
      - name: Install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: imagick, swoole
      - name: install composer dep
        run: composer install
      
